version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - app-network
networks:
  app-network:
